packages:
  - packages/*
  - utils

catalogMode: prefer

catalogs:
  styles:
    '@unocss/astro': ^66.6.0
    '@unocss/reset': ^66.6.0
    unocss: ^66.6.0
  icons:
    '@iconify-json/tabler': ^1.2.26
  build:
    babel-plugin-react-compiler: ^1.0.0
    tsdown: ^0.20.0-beta.3
  docs:
    '@astrojs/starlight': ^0.37.6
    astro: ^5.17.3
  framework:
    react: ^19.2.3
    react-dom: ^19.2.3
    vue: ^3.5.26
  lint:
    '@antfu/eslint-config': ^7.0.1
    '@eslint-react/eslint-plugin': ^2.7.2
    eslint: ^9.39.2
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    eslint-plugin-storybook: ^10.1.11
    eslint-plugin-astro: ^1.6.0
  node:
    bumpp: ^10.4.0
    plop: ^4.0.4
    taze: ^19.9.2
  prod:
    '@destyler/anatomy': ^0.2.6
    '@destyler/aspect-ratio': ^0.2.6
    '@destyler/auto-resize': ^0.2.6
    '@destyler/breadcrumbs': ^0.2.6
    '@destyler/calendar': ^0.2.6
    '@destyler/carousel': ^0.2.6
    '@destyler/checkbox': ^0.2.6
    '@destyler/clipboard': ^0.2.6
    '@destyler/collapse': ^0.2.6
    '@destyler/collapsible': ^0.2.6
    '@destyler/collection': ^0.2.6
    '@destyler/color-picker': ^0.2.6
    '@destyler/combobox': ^0.2.6
    '@destyler/dialog': ^0.2.6
    '@destyler/dom': ^0.2.6
    '@destyler/dynamic': ^0.2.6
    '@destyler/edit': ^0.2.6
    '@destyler/file-upload': ^0.2.6
    '@destyler/floating-panel': ^0.2.6
    '@destyler/focus-trap': ^0.2.6
    '@destyler/highlight-text': ^0.2.6
    '@destyler/hover-card': ^0.2.6
    '@destyler/i18n': ^0.2.6
    '@destyler/image': ^0.2.6
    '@destyler/label': ^0.2.6
    '@destyler/menu': ^0.2.6
    '@destyler/navigation-menu': ^0.2.6
    '@destyler/number-input': ^0.2.6
    '@destyler/otp-input': ^0.2.6
    '@destyler/pagination': ^0.2.6
    '@destyler/popover': ^0.2.6
    '@destyler/presence': ^0.2.6
    '@destyler/progress': ^0.2.6
    '@destyler/qr-code': ^0.2.6
    '@destyler/radio': ^0.2.6
    '@destyler/react': ^0.2.6
    '@destyler/scroll-area': ^0.2.6
    '@destyler/select': ^0.2.6
    '@destyler/separator': ^0.2.6
    '@destyler/signature': ^0.2.6
    '@destyler/slider': ^0.2.6
    '@destyler/splitter': ^0.2.6
    '@destyler/steps': ^0.2.6
    '@destyler/switch': ^0.2.6
    '@destyler/tabs': ^0.2.6
    '@destyler/timer': ^0.2.6
    '@destyler/toast': ^0.2.6
    '@destyler/toggle': ^0.2.6
    '@destyler/tooltip': ^0.2.6
    '@destyler/tour': ^0.2.6
    '@destyler/tree': ^0.2.6
    '@destyler/types': ^0.2.6
    '@destyler/utils': ^0.2.6
    '@destyler/vue': ^0.2.6
    '@destyler/xstate': ^0.2.6
  runtime:
    '@vitejs/devtools': 0.0.0-alpha.21
    '@vitejs/plugin-react': ^5.1.2
    '@vitejs/plugin-vue': ^6.0.3
    vite: ^8.0.0-beta.3
  stories:
    '@chromatic-com/storybook': ^5.0.0
    '@storybook/addon-a11y': ^10.1.11
    '@storybook/addon-docs': ^10.1.11
    '@storybook/addon-vitest': ^10.1.11
    '@storybook/react-vite': ^10.1.11
    '@storybook/vue3-vite': ^10.1.11
    storybook: ^10.1.11
  test:
    '@vitest/browser-playwright': ^4.0.17
    '@vitest/coverage-v8': ^4.0.17
    '@vitest/ui': ^4.0.17
    happy-dom: ^20.3.3
    playwright: ^1.57.0
    vitest: ^4.0.17
    vitest-browser-react: ^2.0.2
    vitest-browser-vue: ^2.0.1
  types:
    '@types/node': ^25.0.9
    '@types/react': ^19.2.8
    '@types/react-dom': ^19.2.3
    tslib: ^2.8.1
    typescript: ^5.9.3
    vue-tsc: ^3.2.2

onlyBuiltDependencies:
  - esbuild
  - sharp

shellEmulator: true
