catalogMode: prefer
shellEmulator: true

trustPolicy: no-downgrade

packages:
  - packages/*
  - utils
catalogs:
  build:
    tsdown: ^0.17.2
  framework:
    vue: ^3.5.25
  lint:
    '@antfu/eslint-config': ^6.5.1
    eslint: ^9.39.1
    eslint-plugin-storybook: ^10.1.5
  node:
    bumpp: ^10.3.2
    plop: ^4.0.4
  prod:
    '@destyler/anatomy': ^0.2.3-beta.2
    '@destyler/auto-resize': ^0.2.3-beta.2
    '@destyler/calendar': ^0.2.3-beta.2
    '@destyler/carousel': ^0.2.3-beta.2
    '@destyler/checkbox': ^0.2.3-beta.2
    '@destyler/clipboard': ^0.2.3-beta.2
    '@destyler/collapse': ^0.2.3-beta.2
    '@destyler/collapsible': ^0.2.3-beta.2
    '@destyler/collection': ^0.2.3-beta.2
    '@destyler/color-picker': ^0.2.3-beta.2
    '@destyler/combobox': ^0.2.3-beta.2
    '@destyler/dialog': ^0.2.3-beta.2
    '@destyler/dom': ^0.2.3-beta.2
    '@destyler/edit': ^0.2.3-beta.2
    '@destyler/focus-trap': ^0.2.3-beta.2
    '@destyler/highlight-text': ^0.2.3-beta.2
    '@destyler/i18n': ^0.2.3-beta.2
    '@destyler/image': ^0.2.3-beta.2
    '@destyler/presence': ^0.2.3-beta.2
    '@destyler/utils': ^0.2.3-beta.2
    '@destyler/vue': ^0.2.3-beta.2
    '@destyler/xstate': ^0.2.3-beta.2
  runtime:
    '@vitejs/devtools': 0.0.0-alpha.19
    '@vitejs/plugin-vue': ^6.0.2
    vite: ^8.0.0-beta.1
  stories:
    '@chromatic-com/storybook': ^4.1.3
    '@storybook/addon-a11y': ^10.1.5
    '@storybook/addon-docs': ^10.1.5
    '@storybook/addon-vitest': ^10.1.5
    '@storybook/vue3-vite': ^10.1.5
    storybook: ^10.1.5
  test:
    '@vitest/browser-playwright': ^4.0.15
    '@vitest/coverage-v8': ^4.0.15
    '@vitest/ui': ^4.0.15
    happy-dom: ^20.0.11
    playwright: ^1.57.0
    vitest: ^4.0.15
    vitest-browser-vue: ^2.0.1
  types:
    '@types/node': ^24.10.2
    tslib: ^2.8.1
    typescript: ^5.9.3
    vue-tsc: ^3.1.8
onlyBuiltDependencies:
  - esbuild
  - sharp
