import type {
  CollectionItem,
  UseAspectRatioProps,
  UseCalendarProps,
  UseCarouselProps,
  UseCheckboxGroupProps,
  UseCheckboxProps,
  UseCollapseProps,
  UseCollapsibleProps,
  UseColorPickerProps,
  UseComboboxProps,
  UseDialogProps,
  UseDynamicProps,
  UseEditProps,
  UseFloatingPanelProps,
  UseHoverCardProps,
  UseMenuProps,
  UseNavigationMenuProps,
  UseNumberInputProps,
  UseOtpInputProps,
  UsePaginationProps,
  UsePopoverProps,
  UseProgressProps,
  UseQrCodeProps,
  UseRadioProps,
  UseScrollAreaProps,
  UseSelectProps,
  UseSliderProps,
  UseSplitterProps,
  UseStepsProps,
  UseSwitchProps,
  UseTabsProps,
  UseToggleGroupProps,
  UseToggleProps,
  UseTooltipProps,
  UseTreeProps,
} from '$lib'

type Has<T, Key extends PropertyKey> = Key extends keyof T ? true : false
type Assert<Value extends true> = Value

export type DefaultPropContract = [
  Assert<Has<UseAspectRatioProps, 'defaultRatio'>>,
  Assert<Has<UseCalendarProps, 'defaultOpen' | 'defaultValue' | 'defaultView'>>,
  Assert<Has<UseCarouselProps, 'defaultPage'>>,
  Assert<Has<UseCheckboxProps, 'defaultChecked'>>,
  Assert<Has<UseCheckboxGroupProps, 'defaultValue'>>,
  Assert<Has<UseCollapseProps, 'defaultValue'>>,
  Assert<Has<UseCollapsibleProps, 'defaultOpen'>>,
  Assert<Has<UseColorPickerProps, 'defaultOpen' | 'defaultValue'>>,
  Assert<Has<UseComboboxProps<CollectionItem>, 'defaultOpen' | 'defaultValue'>>,
  Assert<Has<UseDialogProps, 'defaultOpen'>>,
  Assert<Has<UseDynamicProps, 'defaultValue'>>,
  Assert<Has<UseEditProps, 'defaultEdit' | 'defaultValue'>>,
  Assert<Has<UseFloatingPanelProps, 'defaultOpen'>>,
  Assert<Has<UseHoverCardProps, 'defaultOpen'>>,
  Assert<Has<UseMenuProps, 'defaultOpen'>>,
  Assert<Has<UseNavigationMenuProps, 'defaultValue'>>,
  Assert<Has<UseNumberInputProps, 'defaultValue'>>,
  Assert<Has<UseOtpInputProps, 'defaultValue'>>,
  Assert<Has<UsePaginationProps, 'defaultPage'>>,
  Assert<Has<UsePopoverProps, 'defaultOpen'>>,
  Assert<Has<UseProgressProps, 'defaultValue'>>,
  Assert<Has<UseQrCodeProps, 'defaultValue'>>,
  Assert<Has<UseRadioProps, 'defaultValue'>>,
  Assert<Has<UseScrollAreaProps, 'defaultScrollTop' | 'defaultScrollLeft'>>,
  Assert<Has<UseSelectProps<CollectionItem>, 'defaultOpen' | 'defaultValue'>>,
  Assert<Has<UseSliderProps, 'defaultValue'>>,
  Assert<Has<UseSplitterProps, 'defaultSize'>>,
  Assert<Has<UseStepsProps, 'defaultStep'>>,
  Assert<Has<UseSwitchProps, 'defaultChecked'>>,
  Assert<Has<UseTabsProps, 'defaultValue'>>,
  Assert<Has<UseToggleProps, 'defaultPressed'>>,
  Assert<Has<UseToggleGroupProps, 'defaultValue'>>,
  Assert<Has<UseTooltipProps, 'defaultOpen'>>,
  Assert<Has<UseTreeProps<CollectionItem>, 'defaultSelectedValue' | 'defaultExpandedValue'>>,
]
