import type {
  AspectRatioRootProps,
  AvatarRootProps,
  BreadcrumbsRootProps,
  CalendarRootProps,
  CarouselRootProps,
  CheckboxRootProps,
  ClipboardRootProps,
  CollapseRootProps,
  CollapsibleRootProps,
  CollectionItem,
  ColorPickerRootProps,
  ComboboxRootProps,
  DialogRootProps,
  DynamicRootProps,
  EditRootProps,
  FieldRootProps,
  FieldsetRootProps,
  FileUploadRootProps,
  FloatingPanelRootProps,
  HoverCardRootProps,
  LabelRootProps,
  MenuRootProps,
  NavigationMenuRootProps,
  NumberInputRootProps,
  OtpInputRootProps,
  PaginationRootProps,
  PopoverRootProps,
  ProgressRootProps,
  QrCodeRootProps,
  RadioRootProps,
  ScrollAreaRootProps,
  SelectRootProps,
  SeparatorRootProps,
  SignatureRootProps,
  SliderRootProps,
  SplitterRootProps,
  StepsRootProps,
  SwitchRootProps,
  TabsRootProps,
  TimerRootProps,
  ToggleGroupRootProps,
  TooltipRootProps,
  TreeRootProps,
  UseAspectRatioProps,
  UseAvatarProps,
  UseBreadcrumbsProps,
  UseCalendarProps,
  UseCarouselProps,
  UseCheckboxProps,
  UseClipboardProps,
  UseCollapseProps,
  UseCollapsibleProps,
  UseColorPickerProps,
  UseComboboxProps,
  UseDialogProps,
  UseDynamicProps,
  UseEditProps,
  UseFieldProps,
  UseFieldsetProps,
  UseFileUploadProps,
  UseFloatingPanelProps,
  UseHoverCardProps,
  UseLabelProps,
  UseMenuProps,
  UseNavigationMenuProps,
  UseNumberInputProps,
  UseOtpInputProps,
  UsePaginationProps,
  UsePopoverProps,
  UseProgressProps,
  UseQrCodeProps,
  UseRadioProps,
  UseScrollAreaProps,
  UseSelectProps,
  UseSeparatorProps,
  UseSignatureProps,
  UseSliderProps,
  UseSplitterProps,
  UseStepsProps,
  UseSwitchProps,
  UseTabsProps,
  UseTimerProps,
  UseToggleGroupProps,
  UseTooltipProps,
  UseTourProps,
  UseTreeProps,
} from '$lib'

type IsRequired<T, Key extends keyof T> = object extends Pick<T, Key> ? false : true
type IsOptional<T, Key extends keyof T> = object extends Pick<T, Key> ? true : false
type Assert<Value extends true> = Value

export type HookIdContract = [
  Assert<IsRequired<UseAspectRatioProps, 'id'>>,
  Assert<IsRequired<UseAvatarProps, 'id'>>,
  Assert<IsRequired<UseBreadcrumbsProps, 'id'>>,
  Assert<IsRequired<UseCalendarProps, 'id'>>,
  Assert<IsRequired<UseCarouselProps, 'id'>>,
  Assert<IsRequired<UseCheckboxProps, 'id'>>,
  Assert<IsRequired<UseClipboardProps, 'id'>>,
  Assert<IsRequired<UseCollapseProps, 'id'>>,
  Assert<IsRequired<UseCollapsibleProps, 'id'>>,
  Assert<IsRequired<UseColorPickerProps, 'id'>>,
  Assert<IsRequired<UseComboboxProps<CollectionItem>, 'id'>>,
  Assert<IsRequired<UseDialogProps, 'id'>>,
  Assert<IsRequired<UseDynamicProps, 'id'>>,
  Assert<IsRequired<UseEditProps, 'id'>>,
  Assert<IsRequired<UseFieldProps, 'id'>>,
  Assert<IsRequired<UseFieldsetProps, 'id'>>,
  Assert<IsRequired<UseFileUploadProps, 'id'>>,
  Assert<IsRequired<UseFloatingPanelProps, 'id'>>,
  Assert<IsRequired<UseHoverCardProps, 'id'>>,
  Assert<IsRequired<UseLabelProps, 'id'>>,
  Assert<IsRequired<UseMenuProps, 'id'>>,
  Assert<IsRequired<UseNavigationMenuProps, 'id'>>,
  Assert<IsRequired<UseNumberInputProps, 'id'>>,
  Assert<IsRequired<UseOtpInputProps, 'id'>>,
  Assert<IsRequired<UsePaginationProps, 'id'>>,
  Assert<IsRequired<UsePopoverProps, 'id'>>,
  Assert<IsRequired<UseProgressProps, 'id'>>,
  Assert<IsRequired<UseQrCodeProps, 'id'>>,
  Assert<IsRequired<UseRadioProps, 'id'>>,
  Assert<IsRequired<UseScrollAreaProps, 'id'>>,
  Assert<IsRequired<UseSelectProps<CollectionItem>, 'id'>>,
  Assert<IsRequired<UseSeparatorProps, 'id'>>,
  Assert<IsRequired<UseSignatureProps, 'id'>>,
  Assert<IsRequired<UseSliderProps, 'id'>>,
  Assert<IsRequired<UseSplitterProps, 'id'>>,
  Assert<IsRequired<UseStepsProps, 'id'>>,
  Assert<IsRequired<UseSwitchProps, 'id'>>,
  Assert<IsRequired<UseTabsProps, 'id'>>,
  Assert<IsRequired<UseTimerProps, 'id'>>,
  Assert<IsRequired<UseToggleGroupProps, 'id'>>,
  Assert<IsRequired<UseTooltipProps, 'id'>>,
  Assert<IsRequired<UseTourProps, 'id'>>,
  Assert<IsRequired<UseTreeProps<CollectionItem>, 'id'>>,
]

export type RootIdContract = [
  Assert<IsOptional<AspectRatioRootProps, 'id'>>,
  Assert<IsOptional<AvatarRootProps, 'id'>>,
  Assert<IsOptional<BreadcrumbsRootProps, 'id'>>,
  Assert<IsOptional<CalendarRootProps, 'id'>>,
  Assert<IsOptional<CarouselRootProps, 'id'>>,
  Assert<IsOptional<CheckboxRootProps, 'id'>>,
  Assert<IsOptional<ClipboardRootProps, 'id'>>,
  Assert<IsOptional<CollapseRootProps, 'id'>>,
  Assert<IsOptional<CollapsibleRootProps, 'id'>>,
  Assert<IsOptional<ColorPickerRootProps, 'id'>>,
  Assert<IsOptional<ComboboxRootProps<CollectionItem>, 'id'>>,
  Assert<IsOptional<DialogRootProps, 'id'>>,
  Assert<IsOptional<DynamicRootProps, 'id'>>,
  Assert<IsOptional<EditRootProps, 'id'>>,
  Assert<IsOptional<FieldRootProps, 'id'>>,
  Assert<IsOptional<FieldsetRootProps, 'id'>>,
  Assert<IsOptional<FileUploadRootProps, 'id'>>,
  Assert<IsOptional<FloatingPanelRootProps, 'id'>>,
  Assert<IsOptional<HoverCardRootProps, 'id'>>,
  Assert<IsOptional<LabelRootProps, 'id'>>,
  Assert<IsOptional<MenuRootProps, 'id'>>,
  Assert<IsOptional<NavigationMenuRootProps, 'id'>>,
  Assert<IsOptional<NumberInputRootProps, 'id'>>,
  Assert<IsOptional<OtpInputRootProps, 'id'>>,
  Assert<IsOptional<PaginationRootProps, 'id'>>,
  Assert<IsOptional<PopoverRootProps, 'id'>>,
  Assert<IsOptional<ProgressRootProps, 'id'>>,
  Assert<IsOptional<QrCodeRootProps, 'id'>>,
  Assert<IsOptional<RadioRootProps, 'id'>>,
  Assert<IsOptional<ScrollAreaRootProps, 'id'>>,
  Assert<IsOptional<SelectRootProps<CollectionItem>, 'id'>>,
  Assert<IsOptional<SeparatorRootProps, 'id'>>,
  Assert<IsOptional<SignatureRootProps, 'id'>>,
  Assert<IsOptional<SliderRootProps, 'id'>>,
  Assert<IsOptional<SplitterRootProps, 'id'>>,
  Assert<IsOptional<StepsRootProps, 'id'>>,
  Assert<IsOptional<SwitchRootProps, 'id'>>,
  Assert<IsOptional<TabsRootProps, 'id'>>,
  Assert<IsOptional<TimerRootProps, 'id'>>,
  Assert<IsOptional<ToggleGroupRootProps, 'id'>>,
  Assert<IsOptional<TooltipRootProps, 'id'>>,
  Assert<IsOptional<TreeRootProps<CollectionItem>, 'id'>>,
]
